@startuml
title Diagrama de Atividades - Cadastro de Novo Animal

!theme spacelab

start
:Usuário clica em 'Anunciar Animal';
:Sistema exibe formulário de cadastro;
:Usuário preenche os dados do animal;
:Usuário faz upload de até 5 imagens;

if (Dados são válidos no frontend? (validação com Zod)) then (sim)
  :Frontend envia requisição POST para a rota /animals;
  :Backend recebe dados e imagens (usando Multer);
  :Backend salva informações no banco de dados (usando Prisma);
  :Sistema retorna mensagem de "Anúncio criado com sucesso";
else (não)
  :Sistema exibe mensagens de erro no formulário;
endif

stop
@enduml