@startuml

title Diagrama de Classes Detalhado - Adote Fácil

!theme spacelab

enum AnimalStatus {
  available
  adopted
  removed
}
class User {
  +id: String
  +name: String
  +email: String
  +password: String
  +createdAt: DateTime
  +updatedAt: DateTime
}

class Animal {
  +id: String
  +userId: String
  +name: String
  +type: String
  +gender: String
  ' Atributos opcionais, conforme a nota no diagrama
  +race: String
  +description: String
  +status: AnimalStatus
  +createdAt: DateTime
  +updatedAt: DateTime
}

class AnimalImage {
  +id: String
  +animalId: String
  +imageData: Buffer
  +createdAt: DateTime
}

class Chat {
  +id: String
  +userId1: String
  +userId2: String
  +createdAt: DateTime
  +updatedAt: DateTime
}

class UserMessage {
  +id: String
  +chatId: String
  +senderId: String
  +content: String
  +createdAt: DateTime
  +updatedAt: DateTime
}

User "1" -- "0..*" Animal : dono

Animal "1" -- "0..*" AnimalImage : imagens

Animal ..> AnimalStatus

Chat "1" -- "1..*" UserMessage : mensagens
UserMessage "0..*" -- "1" User : sender
Chat "0..*" -- "1" User : user1
Chat "0..*" -- "1" User : user2

@enduml
