@startuml

title Diagrama de Componentes Detalhado - Adote Fácil

!theme spacelab

actor User

package "Frontend (Aplicação Web)" {
  
  package "Páginas (UI)" {
    [Pagina de Animal]
    [Pagina de Chats]
    [Pagina de Perfil]
    [Pagina de Login]
    [Pagina de Cadastro]
    [Pagina de Chat]
  }

  package "Serviços do Frontend" {
    [Serviço de API]
    [Serviço de Autenticação]
    [Serviço de Animais]
    [Serviço de Chat]
  }
}

package "Backend (Servidor)" {
  
  interface "System API Interface" as IAPI
  
  package "Controllers" {
    [AnimalController]
    [UserController]
    [AuthController]
    [ChatMessageController]
    [ChatController]
  }

  package "Use Cases (Serviços)" {
    [CreateAnimalUseCase]
    [ListAnimalUseCase]
    [UpdateAnimalUseCase]
    [CreateUserUseCase]
    [UpdateUserUseCase]
    [AuthenticateUserUseCase]
    [CreateChatMessageUseCase]
    [ListChatMessageUseCase]
    [CreateChatUseCase]
    [ListChatUseCase]
  }

  package "Repositories (Abstração do DB)" {
    [AnimalRepository]
    [UserRepository]
    [ChatMessageRepository]
    [ChatRepository]
  }
  
  package "ORM" {
    [Prisma ORM]
  }
  
  package "Database" {
    [PostgreSQL Driver]
    [PostgreSQL]
  }
}

User ..> [Pagina de Login]
User ..> [Pagina de Cadastro]

[Pagina de Animal] ..> [Serviço de Animais]
[Pagina de Chats] ..> [Serviço de Chat]
[Pagina de Login] ..> [Serviço de Autenticação]
[Serviço de Autenticação] ..> [Serviço de API]

[Serviço de API] ..> IAPI


IAPI <.. [AnimalController]
IAPI <.. [UserController]
IAPI <.. [AuthController]
IAPI <.. [ChatMessageController]
IAPI <.. [ChatController]

[AnimalController] ..> [CreateAnimalUseCase]
[AnimalController] ..> [ListAnimalUseCase]
[AnimalController] ..> [UpdateAnimalUseCase]
[UserController] ..> [CreateUserUseCase]
[UserController] ..> [UpdateUserUseCase]
[AuthController] ..> [AuthenticateUserUseCase]
[ChatMessageController] ..> [CreateChatMessageUseCase]
[ChatMessageController] ..> [ListChatMessageUseCase]
[ChatController] ..> [CreateChatUseCase]
[ChatController] ..> [ListChatUseCase]

[CreateAnimalUseCase] ..> [AnimalRepository]
[ListAnimalUseCase] ..> [AnimalRepository]
[UpdateAnimalUseCase] ..> [AnimalRepository]
[CreateUserUseCase] ..> [UserRepository]
[UpdateUserUseCase] ..> [UserRepository]
[AuthenticateUserUseCase] ..> [UserRepository]
[CreateChatMessageUseCase] ..> [ChatMessageRepository]
[ListChatMessageUseCase] ..> [ChatMessageRepository]
[CreateChatUseCase] ..> [ChatRepository]
[ListChatUseCase] ..> [ChatRepository]

[AnimalRepository] ..> [Prisma ORM]
[UserRepository] ..> [Prisma ORM]
[ChatMessageRepository] ..> [Prisma ORM]
[ChatRepository] ..> [Prisma ORM]

[Prisma ORM] ..> [PostgreSQL Driver]
[PostgreSQL Driver] ..> [PostgreSQL]

@enduml
